version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"   
  php:
    build: ./docker/php
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    volumes: ['./symfony/:/var/www/symfony:cached']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql